# generated by appcreator
from django.urls import path
from . import dal_views

app_name = 'vocabs'
urlpatterns = [
    path(
        'concept',
        dal_views.SkosConceptAC.as_view(),
        name='concept-ac'
    ),
]