# generated by appcreator
from django.contrib import admin
from .models import (
    Analyse,
    Artifact,
    Geography,
    Institution,
    Number,
    Quarry,
    QuarryGroup,
    Sample,
    DataSheet,
    Project,
)

admin.site.register(Analyse)
admin.site.register(Artifact)
admin.site.register(Geography)
admin.site.register(Institution)
admin.site.register(Number)
admin.site.register(Quarry)
admin.site.register(QuarryGroup)
admin.site.register(Sample)
admin.site.register(DataSheet)
admin.site.register(Project)
