# generated by appcreator
from django.urls import path
from . import dal_views

app_name = "archiv"
urlpatterns = [
    path(
        "analyse-autocomplete/",
        dal_views.AnalyseAC.as_view(),
        name="analyse-autocomplete",
    ),
    path(
        "artifact-autocomplete/",
        dal_views.ArtifactAC.as_view(),
        name="artifact-autocomplete",
    ),
    path(
        "geography-autocomplete/",
        dal_views.GeographyAC.as_view(),
        name="geography-autocomplete",
    ),
    path(
        "institution-autocomplete/",
        dal_views.InstitutionAC.as_view(),
        name="institution-autocomplete",
    ),
    path(
        "number-autocomplete/", dal_views.NumberAC.as_view(), name="number-autocomplete"
    ),
    path(
        "quarry-autocomplete/", dal_views.QuarryAC.as_view(), name="quarry-autocomplete"
    ),
    path(
        "quarrygroup-autocomplete/",
        dal_views.QuarryGroupAC.as_view(),
        name="quarrygroup-autocomplete",
    ),
    path(
        "sample-autocomplete/", dal_views.SampleAC.as_view(), name="sample-autocomplete"
    ),
]
