# generated by appcreator
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Fieldset
from crispy_forms.bootstrap import Accordion, AccordionGroup

from vocabs.models import SkosConcept
from . models import (
    Analyse,
    Artifact,
    Geography,
    Institution,
    Number,
    Quarry,
    QuarryGroup,
    Sample
)


class AnalyseFilterFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(AnalyseFilterFormHelper, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.form_class = 'genericFilterForm'
        self.form_method = 'GET'
        self.helper.form_tag = False
        self.add_input(Submit('Filter', 'Search'))
        self.layout = Layout(
            Fieldset(
                'Basic search options',
                'id',
                css_id="basic_search_fields"
            ),
            Accordion(
                AccordionGroup(
                    'Advanced search',
                    'oeai_inventory_number',
                    'institute',
                    'analyse_type',
                    'date',
                    'notes_thinsection',
                    css_id="more"
                ),
                AccordionGroup(
                    'admin',
                    'legacy_id',
                    css_id="admin_search"
                ),
            )
        )


class AnalyseForm(forms.ModelForm):
    analyse_type = forms.ModelChoiceField(
        required=False,
        label="analyse typ",
        queryset=SkosConcept.objects.filter(collection__pref_label="analyse_type")
    )

    class Meta:
        model = Analyse
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(AnalyseForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'
        self.helper.add_input(Submit('submit', 'save'),)


class ArtifactFilterFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(ArtifactFilterFormHelper, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.form_class = 'genericFilterForm'
        self.form_method = 'GET'
        self.helper.form_tag = False
        self.add_input(Submit('Filter', 'Search'))
        self.layout = Layout(
            Fieldset(
                'Basic search options',
                'id',
                css_id="basic_search_fields"
            ),
            Accordion(
                AccordionGroup(
                    'Advanced search',
                    'artefact_type',
                    'description',
                    'find_spot',
                    'find_spot_extra',
                    'storage_place',
                    'material',
                    'measurement',
                    'preservation',
                    'dating',
                    'images',
                    'literature',
                    css_id="more"
                ),
                AccordionGroup(
                    'admin',
                    'legacy_id',
                    css_id="admin_search"
                ),
            )
        )


class ArtifactForm(forms.ModelForm):
    artefact_type = forms.ModelChoiceField(
        required=False,
        label="artefact type",
        queryset=SkosConcept.objects.filter(collection__pref_label="artefact_type")
    )
    material = forms.ModelChoiceField(
        required=False,
        label="material",
        queryset=SkosConcept.objects.filter(collection__pref_label="material")
    )
    dating = forms.ModelChoiceField(
        required=False,
        label="dating",
        queryset=SkosConcept.objects.filter(collection__pref_label="dating")
    )

    class Meta:
        model = Artifact
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(ArtifactForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'
        self.helper.add_input(Submit('submit', 'save'),)


class GeographyFilterFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(GeographyFilterFormHelper, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.form_class = 'genericFilterForm'
        self.form_method = 'GET'
        self.helper.form_tag = False
        self.add_input(Submit('Filter', 'Search'))
        self.layout = Layout(
            Fieldset(
                'Basic search options',
                'id',
                css_id="basic_search_fields"
            ),
            Accordion(
                AccordionGroup(
                    'Advanced search',
                    'contintent',
                    'land',
                    'province',
                    'location',
                    'name',
                    'identifier',
                    'coordinates',
                    'coordinates',
                    'notes',
                    css_id="more"
                ),
                AccordionGroup(
                    'admin',
                    'legacy_id',
                    css_id="admin_search"
                ),
            )
        )


class GeographyForm(forms.ModelForm):
    contintent = forms.ModelChoiceField(
        required=False,
        label="continent",
        queryset=SkosConcept.objects.filter(collection__pref_label="contintent")
    )
    land = forms.ModelChoiceField(
        required=False,
        label="land",
        queryset=SkosConcept.objects.filter(collection__pref_label="land")
    )
    province = forms.ModelChoiceField(
        required=False,
        label="province",
        queryset=SkosConcept.objects.filter(collection__pref_label="province")
    )
    location = forms.ModelChoiceField(
        required=False,
        label="location",
        queryset=SkosConcept.objects.filter(collection__pref_label="location")
    )
    name = forms.ModelChoiceField(
        required=False,
        label="name",
        queryset=SkosConcept.objects.filter(collection__pref_label="name")
    )

    class Meta:
        model = Geography
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(GeographyForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'
        self.helper.add_input(Submit('submit', 'save'),)


class InstitutionFilterFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(InstitutionFilterFormHelper, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.form_class = 'genericFilterForm'
        self.form_method = 'GET'
        self.helper.form_tag = False
        self.add_input(Submit('Filter', 'Search'))
        self.layout = Layout(
            Fieldset(
                'Basic search options',
                'id',
                css_id="basic_search_fields"
            ),
            Accordion(
                AccordionGroup(
                    'Advanced search',
                    'name',
                    'identifier',
                    css_id="more"
                ),
                AccordionGroup(
                    'admin',
                    'legacy_id',
                    css_id="admin_search"
                ),
            )
        )


class InstitutionForm(forms.ModelForm):

    class Meta:
        model = Institution
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(InstitutionForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'
        self.helper.add_input(Submit('submit', 'save'),)


class NumberFilterFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(NumberFilterFormHelper, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.form_class = 'genericFilterForm'
        self.form_method = 'GET'
        self.helper.form_tag = False
        self.add_input(Submit('Filter', 'Search'))
        self.layout = Layout(
            Fieldset(
                'Basic search options',
                'id',
                css_id="basic_search_fields"
            ),
            Accordion(
                AccordionGroup(
                    'Advanced search',
                    'oeai_inventory_number',
                    'number',
                    'number_type',
                    'institute',
                    'notes',
                    css_id="more"
                ),
                AccordionGroup(
                    'admin',
                    'legacy_id',
                    css_id="admin_search"
                ),
            )
        )


class NumberForm(forms.ModelForm):
    number_type = forms.ModelChoiceField(
        required=False,
        label="number type",
        queryset=SkosConcept.objects.filter(collection__pref_label="number_type")
    )

    class Meta:
        model = Number
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(NumberForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'
        self.helper.add_input(Submit('submit', 'save'),)


class QuarryFilterFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(QuarryFilterFormHelper, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.form_class = 'genericFilterForm'
        self.form_method = 'GET'
        self.helper.form_tag = False
        self.add_input(Submit('Filter', 'Search'))
        self.layout = Layout(
            Fieldset(
                'Basic search options',
                'id',
                css_id="basic_search_fields"
            ),
            Accordion(
                AccordionGroup(
                    'Advanced search',
                    'name',
                    'geography',
                    'images',
                    'description',
                    'literature',
                    css_id="more"
                ),
                AccordionGroup(
                    'admin',
                    'legacy_id',
                    css_id="admin_search"
                ),
            )
        )


class QuarryForm(forms.ModelForm):

    class Meta:
        model = Quarry
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(QuarryForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'
        self.helper.add_input(Submit('submit', 'save'),)


class QuarryGroupFilterFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(QuarryGroupFilterFormHelper, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.form_class = 'genericFilterForm'
        self.form_method = 'GET'
        self.helper.form_tag = False
        self.add_input(Submit('Filter', 'Search'))
        self.layout = Layout(
            Fieldset(
                'Basic search options',
                'id',
                css_id="basic_search_fields"
            ),
            Accordion(
                AccordionGroup(
                    'Advanced search',
                    'name',
                    'description',
                    css_id="more"
                ),
                AccordionGroup(
                    'admin',
                    'legacy_id',
                    css_id="admin_search"
                ),
            )
        )


class QuarryGroupForm(forms.ModelForm):

    class Meta:
        model = QuarryGroup
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(QuarryGroupForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'
        self.helper.add_input(Submit('submit', 'save'),)


class SampleFilterFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(SampleFilterFormHelper, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.form_class = 'genericFilterForm'
        self.form_method = 'GET'
        self.helper.form_tag = False
        self.add_input(Submit('Filter', 'Search'))
        self.layout = Layout(
            Fieldset(
                'Basic search options',
                'id',
                css_id="basic_search_fields"
            ),
            Accordion(
                AccordionGroup(
                    'Advanced search',
                    'oeai_inventory_number',
                    'smell',
                    'grain_size_min',
                    'grain_size_max',
                    'material',
                    'color',
                    'color_description',
                    'color_kodak',
                    'stdcolor',
                    'artefakt_id',
                    'quarry',
                    'quarry_group',
                    'notes',
                    'sampling',
                    'literature',
                    'image',
                    css_id="more"
                ),
                AccordionGroup(
                    'admin',
                    'legacy_id',
                    css_id="admin_search"
                ),
            )
        )


class SampleForm(forms.ModelForm):
    smell = forms.ModelChoiceField(
        required=False,
        label="smell",
        queryset=SkosConcept.objects.filter(collection__pref_label="smell")
    )
    grain_size_min = forms.ModelChoiceField(
        required=False,
        label="grain size min",
        queryset=SkosConcept.objects.filter(collection__pref_label="grain_size_min")
    )
    grain_size_max = forms.ModelChoiceField(
        required=False,
        label="grain size max",
        queryset=SkosConcept.objects.filter(collection__pref_label="grain_size_max")
    )
    material = forms.ModelChoiceField(
        required=False,
        label="material",
        queryset=SkosConcept.objects.filter(collection__pref_label="material")
    )
    color = forms.ModelChoiceField(
        required=False,
        label="color",
        queryset=SkosConcept.objects.filter(collection__pref_label="color")
    )

    class Meta:
        model = Sample
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(SampleForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'
        self.helper.add_input(Submit('submit', 'save'),)


