# generated by appcreator

from django.db import models
from django.urls import reverse
from django.contrib.gis.db.models import MultiPolygonField, PointField

from browsing.browsing_utils import model_to_dict
from vocabs.models import SkosConcept


def set_extra(self, **kwargs):
    self.extra = kwargs
    return self


models.Field.set_extra = set_extra


class Analyse(models.Model):
    ### nan ###
    legacy_id = models.CharField(
        max_length=300, blank=True,
        verbose_name="Legacy ID"
    )
    oeai_inventory_number = models.ForeignKey(
        "Sample",
        related_name='rvn_analyse_oeai_inventory_number_sample',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="OeAI inventory number",
        help_text="OeAI inventory number; unique",
    ).set_extra(
        is_public=True,
    )
    institute = models.ForeignKey(
        "Institution",
        related_name='rvn_analyse_institute_institution',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="institute",
        help_text="institute where the analysis took place",
    ).set_extra(
        is_public=True,
    )
    analyse_type = models.ForeignKey(
        SkosConcept,
        related_name='rvn_analyse_analyse_type_skosconcept',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="analyse typ",
        help_text="analyse typ",
    ).set_extra(
        is_public=True,
    )
    date = models.DateField(
        blank=True, null=True,
        verbose_name="date",
        help_text="analyse date",
    ).set_extra(
        is_public=True,
    )
    notes_thinsection = models.TextField(
        blank=True, null=True,
        verbose_name="thinsection notes",
        help_text="helptext for notes_thinsection",
    ).set_extra(
        is_public=True,
    )
    mgco3 = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="MgCO3",
        help_text="helptext for mgco3",
    ).set_extra(
        is_public=True,
    )
    fe = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="Fe",
        help_text="helptext for fe",
    ).set_extra(
        is_public=True,
    )
    mn = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="Mn",
        help_text="helptext for mn",
    ).set_extra(
        is_public=True,
    )
    sr = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="Sr",
        help_text="helptext for sr",
    ).set_extra(
        is_public=True,
    )
    ion_li = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="Li",
        help_text="helptext for ion_li",
    ).set_extra(
        is_public=True,
    )
    ion_na = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="Na",
        help_text="helptext for ion_na",
    ).set_extra(
        is_public=True,
    )
    ion_k = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="K",
        help_text="helptext for ion_k",
    ).set_extra(
        is_public=True,
    )
    ion_mg = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="MgCO3",
        help_text="helptext for ion_mg",
    ).set_extra(
        is_public=True,
    )
    ion_ca = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="Ca",
        help_text="helptext for ion_ca",
    ).set_extra(
        is_public=True,
    )
    ion_f = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="Fe",
        help_text="helptext for ion_f",
    ).set_extra(
        is_public=True,
    )
    ion_cl = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="Cl",
        help_text="helptext for ion_cl",
    ).set_extra(
        is_public=True,
    )
    ion_br = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="Br",
        help_text="helptext for ion_br",
    ).set_extra(
        is_public=True,
    )
    ion_j = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="J",
        help_text="helptext for ion_j",
    ).set_extra(
        is_public=True,
    )
    ion_no3 = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="NO3",
        help_text="helptext for ion_no3",
    ).set_extra(
        is_public=True,
    )
    ion_so4 = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="SO4",
        help_text="helptext for ion_so4",
    ).set_extra(
        is_public=True,
    )
    ion_li_na = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="Li/Na",
        help_text="helptext for ion_li_na",
    ).set_extra(
        is_public=True,
    )
    ion_k_na = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="K/Na",
        help_text="helptext for ion_k_na",
    ).set_extra(
        is_public=True,
    )
    ion_cl_na = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="Cl/Na",
        help_text="helptext for ion_cl_na",
    ).set_extra(
        is_public=True,
    )
    ion_br_na = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="Br/Na",
        help_text="helptext for ion_br_na",
    ).set_extra(
        is_public=True,
    )
    ion_i_na = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="I/Na",
        help_text="helptext for ion_i_na",
    ).set_extra(
        is_public=True,
    )
    ion_so4_na = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="SO4/Na",
        help_text="helptext for ion_so4_na",
    ).set_extra(
        is_public=True,
    )
    ion_f_na = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="F/Na",
        help_text="helptext for ion_f_na",
    ).set_extra(
        is_public=True,
    )
    ion_no3_na = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="NO3/Na",
        help_text="helptext for ion_no3_na",
    ).set_extra(
        is_public=True,
    )
    iso_d18o = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="d18O (PDB)",
        help_text="helptext for iso_d18o",
    ).set_extra(
        is_public=True,
    )
    iso_d13c = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="D13c (PDB)",
        help_text="helptext for iso_d13c",
    ).set_extra(
        is_public=True,
    )
    icp_mg = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="Mg",
        help_text="helptext for icp_mg",
    ).set_extra(
        is_public=True,
    )
    icp_mn = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="Mn",
        help_text="helptext for icp_mn",
    ).set_extra(
        is_public=True,
    )
    icp_fe = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="Fe",
        help_text="helptext for icp_fe",
    ).set_extra(
        is_public=True,
    )
    icp_sr = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="Sr",
        help_text="helptext for icp_sr",
    ).set_extra(
        is_public=True,
    )
    icp_cr = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="Cr",
        help_text="helptext for icp_cr",
    ).set_extra(
        is_public=True,
    )
    icp_cr_n2o = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="Cr (N2O)",
        help_text="helptext for icp_cr_n2o",
    ).set_extra(
        is_public=True,
    )
    icp_v = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="V",
        help_text="helptext for icp_v",
    ).set_extra(
        is_public=True,
    )
    icp_y = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="Y",
        help_text="helptext for icp_y",
    ).set_extra(
        is_public=True,
    )
    icp_cd = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="Cd",
        help_text="helptext for icp_cd",
    ).set_extra(
        is_public=True,
    )
    icp_ba = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="Ba",
        help_text="helptext for icp_ba",
    ).set_extra(
        is_public=True,
    )
    icp_la = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="La",
        help_text="helptext for icp_la",
    ).set_extra(
        is_public=True,
    )
    icp_ce = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="Ce",
        help_text="helptext for icp_ce",
    ).set_extra(
        is_public=True,
    )
    icp_pr = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="Pr",
        help_text="helptext for icp_pr",
    ).set_extra(
        is_public=True,
    )
    icp_dy = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="Dy",
        help_text="helptext for icp_dy",
    ).set_extra(
        is_public=True,
    )
    icp_ho = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="Ho",
        help_text="helptext for icp_ho",
    ).set_extra(
        is_public=True,
    )
    icp_yb = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="Yb",
        help_text="helptext for icp_yb",
    ).set_extra(
        is_public=True,
    )
    icp_pb = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="Pb",
        help_text="helptext for icp_pb",
    ).set_extra(
        is_public=True,
    )
    icp_u = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="U",
        help_text="helptext for icp_u",
    ).set_extra(
        is_public=True,
    )
    orig_data_csv = models.TextField(
        blank=True,
        null=True,
        verbose_name="The original data"
    ).set_extra(
        is_public=True
    )

    class Meta:

        ordering = [
            'id',
        ]
        verbose_name = "Analyse"

    def __str__(self):
        if self.id:
            return "{}".format(self.id)
        else:
            return "{}".format(self.legacy_id)

    def field_dict(self):
        return model_to_dict(self)

    @classmethod
    def get_listview_url(self):
        return reverse('archiv:analyse_browse')

    @classmethod
    def get_source_table(self):
        return None

    @classmethod
    def get_natural_primary_key(self):
        return "id"

    @classmethod
    def get_createview_url(self):
        return reverse('archiv:analyse_create')

    def get_absolute_url(self):
        return reverse('archiv:analyse_detail', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('archiv:analyse_delete', kwargs={'pk': self.id})

    def get_edit_url(self):
        return reverse('archiv:analyse_edit', kwargs={'pk': self.id})

    def get_next(self):
        next = self.__class__.objects.filter(id__gt=self.id)
        if next:
            return reverse(
                'archiv:analyse_detail',
                kwargs={'pk': next.first().id}
            )
        return False

    def get_prev(self):
        prev = self.__class__.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
            return reverse(
                'archiv:analyse_detail',
                kwargs={'pk': prev.first().id}
            )
        return False


class Artifact(models.Model):
    ### nan ###
    legacy_id = models.CharField(
        max_length=300, blank=True,
        verbose_name="Legacy ID"
    )
    artefact_type = models.ForeignKey(
        SkosConcept,
        related_name='rvn_artifact_artefact_type_skosconcept',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="artefact type",
        help_text="type of the artefact; controlled vocabulary",
    ).set_extra(
        is_public=True,
    )
    description = models.TextField(
        blank=True, null=True,
        verbose_name="description",
        help_text="description of the artefact",
    ).set_extra(
        is_public=True,
    )
    find_spot = models.ForeignKey(
        "Geography",
        related_name='rvn_artifact_find_spot_geography',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="find spot",
        help_text="find spot of the artefact ",
    ).set_extra(
        is_public=True,
    )
    find_spot_extra = models.TextField(
        blank=True, null=True,
        verbose_name="find spot notes",
        help_text="additional notes of the find spot",
    ).set_extra(
        is_public=True,
    )
    storage_place = models.ForeignKey(
        "Institution",
        related_name='rvn_artifact_storage_place_institution',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="storage place",
        help_text="storage institution",
    ).set_extra(
        is_public=True,
    )
    material = models.ForeignKey(
        SkosConcept,
        related_name='rvn_artifact_material_skosconcept',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="material",
        help_text="the artefacts material; controlled vocabulary",
    ).set_extra(
        is_public=True,
    )
    measurement = models.TextField(
        blank=True, null=True,
        verbose_name="measurement",
        help_text="measurement information of the artefact",
    ).set_extra(
        is_public=True,
    )
    preservation = models.TextField(
        blank=True, null=True,
        verbose_name="preservation",
        help_text="preservation information",
    ).set_extra(
        is_public=True,
    )
    dating = models.ForeignKey(
        SkosConcept,
        related_name='rvn_artifact_dating_skosconcept',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="dating",
        help_text="dating information; controlled vocabulary",
    ).set_extra(
        is_public=True,
    )
    images = models.CharField(
        max_length=250,
        blank=True,
        null=True,
        verbose_name="images",
        help_text="images of the artefact",
    ).set_extra(
        is_public=True,
    )
    literature = models.CharField(
        max_length=250,
        blank=True,
        null=True,
        verbose_name="literature",
        help_text="literature",
    ).set_extra(
        is_public=True,
    )
    orig_data_csv = models.TextField(
        blank=True,
        null=True,
        verbose_name="The original data"
    ).set_extra(
        is_public=True
    )

    class Meta:

        ordering = [
            'id',
        ]
        verbose_name = "Artifact"

    def __str__(self):
        if self.id:
            return "{}".format(self.id)
        else:
            return "{}".format(self.legacy_id)

    def field_dict(self):
        return model_to_dict(self)

    @classmethod
    def get_listview_url(self):
        return reverse('archiv:artifact_browse')

    @classmethod
    def get_source_table(self):
        return None

    @classmethod
    def get_natural_primary_key(self):
        return "id"

    @classmethod
    def get_createview_url(self):
        return reverse('archiv:artifact_create')

    def get_absolute_url(self):
        return reverse('archiv:artifact_detail', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('archiv:artifact_delete', kwargs={'pk': self.id})

    def get_edit_url(self):
        return reverse('archiv:artifact_edit', kwargs={'pk': self.id})

    def get_next(self):
        next = self.__class__.objects.filter(id__gt=self.id)
        if next:
            return reverse(
                'archiv:artifact_detail',
                kwargs={'pk': next.first().id}
            )
        return False

    def get_prev(self):
        prev = self.__class__.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
            return reverse(
                'archiv:artifact_detail',
                kwargs={'pk': prev.first().id}
            )
        return False


class Geography(models.Model):
    ### nan ###
    legacy_id = models.CharField(
        max_length=300, blank=True,
        verbose_name="Legacy ID"
    )
    name = models.CharField(
        max_length=250,
        blank=True,
        null=True,
        verbose_name="name",
        help_text="name of the geographic location",
    ).set_extra(
        is_public=True,
    )
    identifier = models.CharField(
        max_length=250,
        blank=True,
        null=True,
        verbose_name="identifier",
        help_text="identifier of the geographic location; gazetteers",
    ).set_extra(
        is_public=True,
    )
    coordinates = PointField(
        blank=True, null=True,
        verbose_name="coordinates",
        help_text="coordinates of the geographic location (X, Y)",
    ).set_extra(
        is_public=True,
    )
    polygon = MultiPolygonField(
        blank=True, null=True,
        verbose_name="polygon",
        help_text="MultiPolygonField to depict the area of the location",
    ).set_extra(
        is_public=True,
    )
    notes = models.TextField(
        blank=True, null=True,
        verbose_name="notes",
        help_text="additional notes",
    ).set_extra(
        is_public=True,
    )
    orig_data_csv = models.TextField(
        blank=True,
        null=True,
        verbose_name="The original data"
    ).set_extra(
        is_public=True
    )

    class Meta:

        ordering = [
            'id',
        ]
        verbose_name = "Geography"

    def __str__(self):
        if self.id:
            return "{}".format(self.id)
        else:
            return "{}".format(self.legacy_id)

    def field_dict(self):
        return model_to_dict(self)

    @classmethod
    def get_listview_url(self):
        return reverse('archiv:geography_browse')

    @classmethod
    def get_source_table(self):
        return None

    @classmethod
    def get_natural_primary_key(self):
        return "id"

    @classmethod
    def get_createview_url(self):
        return reverse('archiv:geography_create')

    def get_absolute_url(self):
        return reverse('archiv:geography_detail', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('archiv:geography_delete', kwargs={'pk': self.id})

    def get_edit_url(self):
        return reverse('archiv:geography_edit', kwargs={'pk': self.id})

    def get_next(self):
        next = self.__class__.objects.filter(id__gt=self.id)
        if next:
            return reverse(
                'archiv:geography_detail',
                kwargs={'pk': next.first().id}
            )
        return False

    def get_prev(self):
        prev = self.__class__.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
            return reverse(
                'archiv:geography_detail',
                kwargs={'pk': prev.first().id}
            )
        return False


class Institution(models.Model):
    ### nan ###
    legacy_id = models.CharField(
        max_length=300, blank=True,
        verbose_name="Legacy ID"
    )
    name = models.CharField(
        max_length=250,
        blank=True,
        null=True,
        verbose_name="name",
        help_text="name of the institution",
    ).set_extra(
        is_public=True,
    )
    identifier = models.CharField(
        max_length=250,
        blank=True,
        null=True,
        verbose_name="identifier",
        help_text="identifier of the institution; gazetteers",
    ).set_extra(
        is_public=True,
    )
    orig_data_csv = models.TextField(
        blank=True,
        null=True,
        verbose_name="The original data"
    ).set_extra(
        is_public=True
    )

    class Meta:

        ordering = [
            'id',
        ]
        verbose_name = "Insititution"

    def __str__(self):
        if self.id:
            return "{}".format(self.id)
        else:
            return "{}".format(self.legacy_id)

    def field_dict(self):
        return model_to_dict(self)

    @classmethod
    def get_listview_url(self):
        return reverse('archiv:institution_browse')

    @classmethod
    def get_source_table(self):
        return None

    @classmethod
    def get_natural_primary_key(self):
        return "id"

    @classmethod
    def get_createview_url(self):
        return reverse('archiv:institution_create')

    def get_absolute_url(self):
        return reverse('archiv:institution_detail', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('archiv:institution_delete', kwargs={'pk': self.id})

    def get_edit_url(self):
        return reverse('archiv:institution_edit', kwargs={'pk': self.id})

    def get_next(self):
        next = self.__class__.objects.filter(id__gt=self.id)
        if next:
            return reverse(
                'archiv:institution_detail',
                kwargs={'pk': next.first().id}
            )
        return False

    def get_prev(self):
        prev = self.__class__.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
            return reverse(
                'archiv:institution_detail',
                kwargs={'pk': prev.first().id}
            )
        return False


class Number(models.Model):
    ### nan ###
    legacy_id = models.CharField(
        max_length=300, blank=True,
        verbose_name="Legacy ID"
    )
    oeai_inventory_number = models.ForeignKey(
        "Sample",
        related_name='rvn_number_oeai_inventory_number_sample',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="OeAI inventory number",
        help_text="OeAI inventory number",
    ).set_extra(
        is_public=True,
    )
    number = models.CharField(
        max_length=250,
        blank=True,
        null=True,
        verbose_name="number",
        help_text="other number",
    ).set_extra(
        is_public=True,
    )
    number_type = models.ForeignKey(
        SkosConcept,
        related_name='rvn_number_number_type_skosconcept',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="number type",
        help_text="type of the number; controlled vocabulary",
    ).set_extra(
        is_public=True,
    )
    institute = models.ForeignKey(
        "Institution",
        related_name='rvn_number_institute_institution',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="institute",
        help_text="institute that assigned then number",
    ).set_extra(
        is_public=True,
    )
    notes = models.TextField(
        blank=True, null=True,
        verbose_name="notes",
        help_text="additional notes",
    ).set_extra(
        is_public=True,
    )
    orig_data_csv = models.TextField(
        blank=True,
        null=True,
        verbose_name="The original data"
    ).set_extra(
        is_public=True
    )

    class Meta:

        ordering = [
            'id',
        ]
        verbose_name = "Number"

    def __str__(self):
        if self.id:
            return "{}".format(self.id)
        else:
            return "{}".format(self.legacy_id)

    def field_dict(self):
        return model_to_dict(self)

    @classmethod
    def get_listview_url(self):
        return reverse('archiv:number_browse')

    @classmethod
    def get_source_table(self):
        return None

    @classmethod
    def get_natural_primary_key(self):
        return "id"

    @classmethod
    def get_createview_url(self):
        return reverse('archiv:number_create')

    def get_absolute_url(self):
        return reverse('archiv:number_detail', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('archiv:number_delete', kwargs={'pk': self.id})

    def get_edit_url(self):
        return reverse('archiv:number_edit', kwargs={'pk': self.id})

    def get_next(self):
        next = self.__class__.objects.filter(id__gt=self.id)
        if next:
            return reverse(
                'archiv:number_detail',
                kwargs={'pk': next.first().id}
            )
        return False

    def get_prev(self):
        prev = self.__class__.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
            return reverse(
                'archiv:number_detail',
                kwargs={'pk': prev.first().id}
            )
        return False


class Quarry(models.Model):
    ### nan ###
    legacy_id = models.CharField(
        max_length=300, blank=True,
        verbose_name="Legacy ID"
    )
    name = models.CharField(
        max_length=250,
        blank=True,
        null=True,
        verbose_name="name",
        help_text="name of the quarry",
    ).set_extra(
        is_public=True,
    )
    geography = models.ForeignKey(
        "Geography",
        related_name='rvn_quarry_geography_geography',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="geographical location",
        help_text="geographical location of the quarry",
    ).set_extra(
        is_public=True,
    )
    images = models.CharField(
        max_length=250,
        blank=True,
        null=True,
        verbose_name="images",
        help_text="images",
    ).set_extra(
        is_public=True,
    )
    description = models.TextField(
        blank=True, null=True,
        verbose_name="description",
        help_text="description of the quarry",
    ).set_extra(
        is_public=True,
    )
    literature = models.CharField(
        max_length=250,
        blank=True,
        null=True,
        verbose_name="literature",
        help_text="literature",
    ).set_extra(
        is_public=True,
    )
    open_access = models.BooleanField(
        default=False,
        blank=True, null=True,
        verbose_name="open access",
        help_text="open access",
    ).set_extra(
        is_public=True,
    )
    orig_data_csv = models.TextField(
        blank=True,
        null=True,
        verbose_name="The original data"
    ).set_extra(
        is_public=True
    )

    class Meta:

        ordering = [
            'id',
        ]
        verbose_name = "Quarry"

    def __str__(self):
        if self.id:
            return "{}".format(self.id)
        else:
            return "{}".format(self.legacy_id)

    def field_dict(self):
        return model_to_dict(self)

    @classmethod
    def get_listview_url(self):
        return reverse('archiv:quarry_browse')

    @classmethod
    def get_source_table(self):
        return None

    @classmethod
    def get_natural_primary_key(self):
        return "id"

    @classmethod
    def get_createview_url(self):
        return reverse('archiv:quarry_create')

    def get_absolute_url(self):
        return reverse('archiv:quarry_detail', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('archiv:quarry_delete', kwargs={'pk': self.id})

    def get_edit_url(self):
        return reverse('archiv:quarry_edit', kwargs={'pk': self.id})

    def get_next(self):
        next = self.__class__.objects.filter(id__gt=self.id)
        if next:
            return reverse(
                'archiv:quarry_detail',
                kwargs={'pk': next.first().id}
            )
        return False

    def get_prev(self):
        prev = self.__class__.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
            return reverse(
                'archiv:quarry_detail',
                kwargs={'pk': prev.first().id}
            )
        return False


class QuarryGroup(models.Model):
    ### nan ###
    legacy_id = models.CharField(
        max_length=300, blank=True,
        verbose_name="Legacy ID"
    )
    name = models.CharField(
        max_length=250,
        blank=True,
        null=True,
        verbose_name="name",
        help_text="name of the quarry group",
    ).set_extra(
        is_public=True,
    )
    description = models.TextField(
        blank=True, null=True,
        verbose_name="description",
        help_text="description of the quarry group",
    ).set_extra(
        is_public=True,
    )
    orig_data_csv = models.TextField(
        blank=True,
        null=True,
        verbose_name="The original data"
    ).set_extra(
        is_public=True
    )

    class Meta:

        ordering = [
            'id',
        ]
        verbose_name = "QuarryGroup"

    def __str__(self):
        if self.id:
            return "{}".format(self.id)
        else:
            return "{}".format(self.legacy_id)

    def field_dict(self):
        return model_to_dict(self)

    @classmethod
    def get_listview_url(self):
        return reverse('archiv:quarrygroup_browse')

    @classmethod
    def get_source_table(self):
        return None

    @classmethod
    def get_natural_primary_key(self):
        return "id"

    @classmethod
    def get_createview_url(self):
        return reverse('archiv:quarrygroup_create')

    def get_absolute_url(self):
        return reverse('archiv:quarrygroup_detail', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('archiv:quarrygroup_delete', kwargs={'pk': self.id})

    def get_edit_url(self):
        return reverse('archiv:quarrygroup_edit', kwargs={'pk': self.id})

    def get_next(self):
        next = self.__class__.objects.filter(id__gt=self.id)
        if next:
            return reverse(
                'archiv:quarrygroup_detail',
                kwargs={'pk': next.first().id}
            )
        return False

    def get_prev(self):
        prev = self.__class__.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
            return reverse(
                'archiv:quarrygroup_detail',
                kwargs={'pk': prev.first().id}
            )
        return False


class Sample(models.Model):
    ### nan ###
    legacy_id = models.CharField(
        max_length=300, blank=True,
        verbose_name="Legacy ID"
    )
    oeai_inventory_number = models.CharField(
        max_length=250,
        blank=True,
        null=True,
        verbose_name="OeAI inventory number",
        help_text="OeAI inventory number; unique",
    ).set_extra(
        is_public=True,
    )
    smell = models.ForeignKey(
        SkosConcept,
        related_name='rvn_sample_smell_skosconcept',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="smell",
        help_text="smell of the sample; entries from 0 to 4",
    ).set_extra(
        is_public=True,
    )
    grain_size_min = models.ForeignKey(
        SkosConcept,
        related_name='rvn_sample_grain_size_min_skosconcept',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="grain size min",
        help_text="minimum grain size; controlled vocabulary",
    ).set_extra(
        is_public=True,
    )
    grain_size_max = models.ForeignKey(
        SkosConcept,
        related_name='rvn_sample_grain_size_max_skosconcept',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="grain size max",
        help_text="maximum grain size; controlled vocabulary",
    ).set_extra(
        is_public=True,
    )
    material = models.ForeignKey(
        SkosConcept,
        related_name='rvn_sample_material_skosconcept',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="material",
        help_text="material of the sample; controlled vocabulary",
    ).set_extra(
        is_public=True,
    )
    color = models.ForeignKey(
        SkosConcept,
        related_name='rvn_sample_color_skosconcept',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="color",
        help_text="color of the sample; controlled vocabulary",
    ).set_extra(
        is_public=True,
    )
    color_description = models.TextField(
        blank=True, null=True,
        verbose_name="color description",
        help_text="precise description of the color",
    ).set_extra(
        is_public=True,
    )
    color_kodak = models.CharField(
        max_length=250,
        blank=True,
        null=True,
        verbose_name="color kodak",
        help_text="more detailed information about the kodak color",
    ).set_extra(
        is_public=True,
    )
    stdcolor = models.CharField(
        max_length=250,
        blank=True,
        null=True,
        verbose_name="color stdcolor",
        help_text="more detailed information about the kodak color",
    ).set_extra(
        is_public=True,
    )
    weight = models.DecimalField(
        max_digits=19,
        decimal_places=10,
        blank=True, null=True,
        verbose_name="weight",
        help_text="weight of the sample",
    ).set_extra(
        is_public=True,
    )
    artefakt_id = models.ForeignKey(
        "Artifact",
        related_name='rvn_sample_artefakt_id_artifact',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="artefact",
        help_text="sampled artefact",
    ).set_extra(
        is_public=True,
    )
    quarry = models.ForeignKey(
        "Quarry",
        related_name='rvn_sample_quarry_quarry',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="quarry",
        help_text="sampled quarry",
    ).set_extra(
        is_public=True,
    )
    quarry_group = models.ForeignKey(
        "QuarryGroup",
        related_name='rvn_sample_quarry_group_quarrygroup',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="quarry group",
        help_text="quarry group",
    ).set_extra(
        is_public=True,
    )
    notes = models.TextField(
        blank=True, null=True,
        verbose_name="notes",
        help_text="notes",
    ).set_extra(
        is_public=True,
    )
    sampling = models.CharField(
        max_length=250,
        blank=True,
        null=True,
        verbose_name="sampling",
        help_text="information about the sampling",
    ).set_extra(
        is_public=True,
    )
    literature = models.CharField(
        max_length=250,
        blank=True,
        null=True,
        verbose_name="literature",
        help_text="literature",
    ).set_extra(
        is_public=True,
    )
    image = models.CharField(
        max_length=250,
        blank=True,
        null=True,
        verbose_name="images",
        help_text="images",
    ).set_extra(
        is_public=True,
    )
    open_access = models.BooleanField(
        default=False,
        blank=True, null=True,
        verbose_name="open access",
        help_text="open access",
    ).set_extra(
        is_public=True,
    )
    orig_data_csv = models.TextField(
        blank=True,
        null=True,
        verbose_name="The original data"
    ).set_extra(
        is_public=True
    )

    class Meta:

        ordering = [
            'id',
        ]
        verbose_name = "Sample"

    def __str__(self):
        if self.oeai_inventory_number:
            return "{}".format(self.oeai_inventory_number)
        else:
            return "{}".format(self.legacy_id)

    def field_dict(self):
        return model_to_dict(self)

    @classmethod
    def get_listview_url(self):
        return reverse('archiv:sample_browse')

    @classmethod
    def get_source_table(self):
        return None

    @classmethod
    def get_natural_primary_key(self):
        return "oeai_inventory_number"

    @classmethod
    def get_createview_url(self):
        return reverse('archiv:sample_create')

    def get_absolute_url(self):
        return reverse('archiv:sample_detail', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('archiv:sample_delete', kwargs={'pk': self.id})

    def get_edit_url(self):
        return reverse('archiv:sample_edit', kwargs={'pk': self.id})

    def get_next(self):
        next = self.__class__.objects.filter(id__gt=self.id)
        if next:
            return reverse(
                'archiv:sample_detail',
                kwargs={'pk': next.first().id}
            )
        return False

    def get_prev(self):
        prev = self.__class__.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
            return reverse(
                'archiv:sample_detail',
                kwargs={'pk': prev.first().id}
            )
        return False


