# generated by appcreator
import django_tables2 as tables

from browsing.browsing_utils import MergeColumn
from . models import (
    Analyse,
    Artifact,
    Geography,
    Institution,
    Number,
    Quarry,
    QuarryGroup,
    Sample
)


class AnalyseTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    merge = MergeColumn(verbose_name='keep | remove', accessor='pk')

    class Meta:
        model = Analyse
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class ArtifactTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    merge = MergeColumn(verbose_name='keep | remove', accessor='pk')

    class Meta:
        model = Artifact
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class GeographyTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    merge = MergeColumn(verbose_name='keep | remove', accessor='pk')

    class Meta:
        model = Geography
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class InstitutionTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    merge = MergeColumn(verbose_name='keep | remove', accessor='pk')

    class Meta:
        model = Institution
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class NumberTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    merge = MergeColumn(verbose_name='keep | remove', accessor='pk')

    class Meta:
        model = Number
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class QuarryTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    merge = MergeColumn(verbose_name='keep | remove', accessor='pk')

    class Meta:
        model = Quarry
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class QuarryGroupTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    merge = MergeColumn(verbose_name='keep | remove', accessor='pk')

    class Meta:
        model = QuarryGroup
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class SampleTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    merge = MergeColumn(verbose_name='keep | remove', accessor='pk')

    class Meta:
        model = Sample
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}

