# generated by appcreator
from django.urls import path
from . import views
from . import ingest_views

app_name = "archiv"
urlpatterns = [
    path("test/", views.count_geo, name="test"),
    path("ingest/", ingest_views.ContactFormView.as_view(), name="ingest"),
    path("task-overview/", views.TaskOveriewView.as_view(), name="task_overview"),
    path("analyse/", views.AnalyseListView.as_view(), name="analyse_browse"),
    path(
        "analyse/detail/<int:pk>",
        views.AnalyseDetailView.as_view(),
        name="analyse_detail",
    ),
    path("analyse/create/", views.AnalyseCreate.as_view(), name="analyse_create"),
    path(
        "analyse/edit/<int:pk>",
        views.AnalyseUpdate.as_view(),
        name="analyse_edit",
    ),
    path(
        "analyse/delete/<int:pk>",
        views.AnalyseDelete.as_view(),
        name="analyse_delete",
    ),
    path("artifact/", views.ArtifactListView.as_view(), name="artifact_browse"),
    path(
        "artifact/detail/<int:pk>",
        views.ArtifactDetailView.as_view(),
        name="artifact_detail",
    ),
    path("artifact/create/", views.ArtifactCreate.as_view(), name="artifact_create"),
    path(
        "artifact/edit/<int:pk>",
        views.ArtifactUpdate.as_view(),
        name="artifact_edit",
    ),
    path(
        "artifact/delete/<int:pk>",
        views.ArtifactDelete.as_view(),
        name="artifact_delete",
    ),
    path("geography/", views.GeographyListView.as_view(), name="geography_browse"),
    path(
        "geography/detail/<int:pk>",
        views.GeographyDetailView.as_view(),
        name="geography_detail",
    ),
    path("geography/create/", views.GeographyCreate.as_view(), name="geography_create"),
    path(
        "geography/edit/<int:pk>",
        views.GeographyUpdate.as_view(),
        name="geography_edit",
    ),
    path(
        "geography/delete/<int:pk>",
        views.GeographyDelete.as_view(),
        name="geography_delete",
    ),
    path(
        "institution/",
        views.InstitutionListView.as_view(),
        name="institution_browse",
    ),
    path(
        "institution/detail/<int:pk>",
        views.InstitutionDetailView.as_view(),
        name="institution_detail",
    ),
    path(
        "institution/create/",
        views.InstitutionCreate.as_view(),
        name="institution_create",
    ),
    path(
        "institution/edit/<int:pk>",
        views.InstitutionUpdate.as_view(),
        name="institution_edit",
    ),
    path(
        "institution/delete/<int:pk>",
        views.InstitutionDelete.as_view(),
        name="institution_delete",
    ),
    path("number/", views.NumberListView.as_view(), name="number_browse"),
    path(
        "number/detail/<int:pk>",
        views.NumberDetailView.as_view(),
        name="number_detail",
    ),
    path("number/create/", views.NumberCreate.as_view(), name="number_create"),
    path(
        "number/edit/<int:pk>",
        views.NumberUpdate.as_view(),
        name="number_edit",
    ),
    path(
        "number/delete/<int:pk>",
        views.NumberDelete.as_view(),
        name="number_delete",
    ),
    path("quarry/", views.QuarryListView.as_view(), name="quarry_browse"),
    path(
        "quarry/detail/<int:pk>",
        views.QuarryDetailView.as_view(),
        name="quarry_detail",
    ),
    path("quarry/create/", views.QuarryCreate.as_view(), name="quarry_create"),
    path(
        "quarry/edit/<int:pk>",
        views.QuarryUpdate.as_view(),
        name="quarry_edit",
    ),
    path(
        "quarry/delete/<int:pk>",
        views.QuarryDelete.as_view(),
        name="quarry_delete",
    ),
    path(
        "quarrygroup/",
        views.QuarryGroupListView.as_view(),
        name="quarrygroup_browse",
    ),
    path(
        "quarrygroup/detail/<int:pk>",
        views.QuarryGroupDetailView.as_view(),
        name="quarrygroup_detail",
    ),
    path(
        "quarrygroup/create/",
        views.QuarryGroupCreate.as_view(),
        name="quarrygroup_create",
    ),
    path(
        "quarrygroup/edit/<int:pk>",
        views.QuarryGroupUpdate.as_view(),
        name="quarrygroup_edit",
    ),
    path(
        "quarrygroup/delete/<int:pk>",
        views.QuarryGroupDelete.as_view(),
        name="quarrygroup_delete",
    ),
    path("sample/", views.SampleListView.as_view(), name="sample_browse"),
    path(
        "sample/detail/<int:pk>",
        views.SampleDetailView.as_view(),
        name="sample_detail",
    ),
    path("sample/create/", views.SampleCreate.as_view(), name="sample_create"),
    path(
        "sample/edit/<int:pk>",
        views.SampleUpdate.as_view(),
        name="sample_edit",
    ),
    path(
        "sample/delete/<int:pk>",
        views.SampleDelete.as_view(),
        name="sample_delete",
    ),
    path(
        "project/",
        views.ProjectListView.as_view(),
        name="project_browse",
    ),
    path(
        "project/detail/<int:pk>",
        views.ProjectDetailView.as_view(),
        name="project_detail",
    ),
    path(
        "project/edit/<int:pk>",
        views.ProjectUpdate.as_view(),
        name="project_edit",
    ),
    path(
        "project/delete/<int:pk>",
        views.ProjectDelete.as_view(),
        name="project_delete",
    ),
    path("project/create/", views.ProjectCreate.as_view(), name="project_create"),

    path(
        "image/detail/<int:pk>",
        views.ImageDetailView.as_view(),
        name="image_detail",
    ),
    path(
        "projects/",
        views.ProjectsView.as_view(),
        name="projects",
    ),
]
