# generated by appcreator
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.serializers import serialize
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView
from django.views.generic import TemplateView
import csv
import io
import zipfile
from django.db.models import Q
from django.shortcuts import render
from django_celery_results.models import TaskResult
from . filters import (
    AnalyseListFilter,
    ArtifactListFilter,
    GeographyListFilter,
    InstitutionListFilter,
    NumberListFilter,
    QuarryListFilter,
    QuarryGroupListFilter,
    SampleListFilter,
    ProjectListFilter
)
from . forms import (
    AnalyseForm, AnalyseFilterFormHelper,
    ArtifactForm, ArtifactFilterFormHelper,
    GeographyForm, GeographyFilterFormHelper,
    InstitutionForm, InstitutionFilterFormHelper,
    NumberForm, NumberFilterFormHelper,
    QuarryForm, QuarryFilterFormHelper,
    QuarryGroupForm, QuarryGroupFilterFormHelper,
    SampleForm, SampleFilterFormHelper,
    ProjectForm, ProjectFilterFormHelper
)
from . tables import (
    AnalyseTable,
    ArtifactTable,
    GeographyTable,
    InstitutionTable,
    NumberTable,
    QuarryTable,
    QuarryGroupTable,
    SampleTable,
    ProjectTable
)
from . models import (
    Analyse,
    Artifact,
    Geography,
    Institution,
    Number,
    Quarry,
    QuarryGroup,
    Sample,
    Project,
    Image
)
from browsing.utils import (
    GenericListView, BaseCreateView, BaseUpdateView, BaseDetailView
)

from archiv.tasks import count_geography

def export_zip(request):
    query = request.GET.get("q", "").strip()
    print(query)

    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zip_file:

        # Helper-Funktion für CSV-Erzeugung
        def write_csv_to_zip(queryset, fieldnames, filename, row_func):
            output = io.StringIO()
            writer = csv.writer(output)
            writer.writerow(fieldnames)
            for obj in queryset:
                writer.writerow(row_func(obj))
            zip_file.writestr(filename, output.getvalue())

            # Artifact
        artifact_ergebnisse = Artifact.objects.filter(
            Q(description__icontains=query) | 
            Q(find_spot_extra__icontains=query) | 
            Q(preservation__icontains=query) |
            Q(material_id__pref_label__icontains=query) |
            Q(find_spot_id__name__icontains=query) |
            Q(storage_place_id__name__icontains=query)
        )
        write_csv_to_zip(
            artifact_ergebnisse,
            ['ID', 'Beschreibung', 'Fundort (extra)', 'Erhaltungszustand', 'Material', 'Fundort', 'Lagerort'],
            'artifacts.csv',
            lambda a: [a.id, a.description, a.find_spot_extra, a.preservation,
                       getattr(a.material_id, 'pref_label', ''), 
                       getattr(a.find_spot_id, 'name', ''), 
                       getattr(a.storage_place_id, 'name', '')]
        )

        # Geography
        geo_ergebnisse = Geography.objects.filter(
            Q(name__icontains=query) | 
            Q(notes__icontains=query) |
            Q(land__icontains=query) |
            Q(location__icontains=query) |
            Q(province__icontains=query)
        )
        write_csv_to_zip(
            geo_ergebnisse,
            ['ID', 'Name', 'Notizen', 'Land', 'Ort', 'Provinz'],
            'geography.csv',
            lambda g: [g.id, g.name, g.notes, g.land, g.location, g.province]
        )

        # Institution
        institution_ergebnisse = Institution.objects.filter(
            Q(name__icontains=query)
        )
        write_csv_to_zip(
            institution_ergebnisse,
            ['ID', 'Name'],
            'institutions.csv',
            lambda i: [i.id, i.name]
        )

        # Project
        project_ergebnisse = Project.objects.filter(
            Q(name__icontains=query) | 
            Q(description__icontains=query) |
            Q(contact_name__icontains=query)
        )
        write_csv_to_zip(
            project_ergebnisse,
            ['ID', 'Name', 'Beschreibung', 'Kontaktperson'],
            'projects.csv',
            lambda p: [p.id, p.name, p.description, p.contact_name]
        )

        # Quarry
        quarry_ergebnisse = Quarry.objects.filter(
            Q(name__icontains=query) | 
            Q(description__icontains=query) |
            Q(geography_id__name__icontains=query)
        )
        write_csv_to_zip(
            quarry_ergebnisse,
            ['ID', 'Name', 'Beschreibung', 'Geographie'],
            'quarries.csv',
            lambda q: [q.id, q.name, q.description, getattr(q.geography_id, 'name', '')]
        )

        # QuarryGroup
        quarrygroup_ergebnisse = QuarryGroup.objects.filter(
            Q(name__icontains=query) | 
            Q(description__icontains=query)
        )
        write_csv_to_zip(
            quarrygroup_ergebnisse,
            ['ID', 'Name', 'Beschreibung'],
            'quarrygroups.csv',
            lambda qg: [qg.id, qg.name, qg.description]
        )

        # Sample
        sample_ergebnisse = Sample.objects.filter(
            Q(oeai_inventory_number__icontains=query) | 
            Q(notes__icontains=query) |
            Q(material_id__pref_label__icontains=query) |
            Q(quarry_id__name__icontains=query) |
            Q(quarry_group_id__name__icontains=query)
        )
        write_csv_to_zip(
            sample_ergebnisse,
            ['ID', 'Inventarnummer', 'Notizen', 'Material', 'Steinbruch', 'Steinbruchgruppe'],
            'samples.csv',
            lambda s: [s.id, s.oeai_inventory_number, s.notes,
                       getattr(s.material_id, 'pref_label', ''),
                       getattr(s.quarry_id, 'name', ''),
                       getattr(s.quarry_group_id, 'name', '')]
        )

        # Number
        number_ergebnisse = Number.objects.filter(
            Q(oeai_inventory_number_id__oeai_inventory_number__icontains=query) | 
            Q(number__icontains=query) |
            Q(number_type__pref_label__icontains=query)
        )
        write_csv_to_zip(
            number_ergebnisse,
            ['ID', 'Nummer', 'Typ', 'Inventarnummer'],
            'numbers.csv',
            lambda n: [n.id, n.number,
                       getattr(n.number_type, 'pref_label', ''),
                       getattr(n.oeai_inventory_number_id, 'oeai_inventory_number', '')]
        )

        # Analyse
        analyse_ergebnisse = Analyse.objects.filter(
            Q(oeai_inventory_number_id__oeai_inventory_number__icontains=query) |
            Q(analyse_type_id__pref_label__icontains=query)
        )
        write_csv_to_zip(
            analyse_ergebnisse,
            ['ID', 'Inventarnummer', 'Analyse-Typ'],
            'analyses.csv',
            lambda a: [a.id,
                       getattr(a.oeai_inventory_number_id, 'oeai_inventory_number', ''),
                       getattr(a.analyse_type_id, 'pref_label', '')]
        )
        
    response = HttpResponse(zip_buffer.getvalue(), content_type='application/zip')
    response['Content-Disposition'] = f'attachment; filename=suche_{query}.zip'
    return response

def explore(request):
    query=request.GET.get("q", "").strip()
    artifact_ergebnisse = []
    geo_ergebnisse = []
    institution_ergebnisse = []
    project_ergebnisse = []
    quarry_ergebnisse = []
    quarrygroup_ergebnisse = []
    sample_ergebnisse = []
    number_ergebnisse = []
    analyse_ergebnisse = []

    if query: 
        artifact_ergebnisse = Artifact.objects.filter(
            Q(description__icontains=query) | 
            Q(find_spot_extra__icontains=query) | 
            Q(preservation__icontains=query) |
            Q(material_id__pref_label__icontains=query) |
            Q(find_spot_id__name__icontains=query) |
            Q(storage_place_id__name__icontains=query)
        )
        geo_ergebnisse = Geography.objects.filter(
            Q(name__icontains=query) | 
            Q(notes__icontains=query) |
            Q(land__icontains=query) |
            Q(location__icontains=query) |
            Q(province__icontains=query)
        )
        institution_ergebnisse = Institution.objects.filter(
            Q(name__icontains=query)
        )
        project_ergebnisse = Project.objects.filter(
            Q(name__icontains=query) | 
            Q(description__icontains=query) |
            Q(contact_name__icontains=query)
        )
        quarry_ergebnisse = Quarry.objects.filter(
            Q(name__icontains=query) | 
            Q(description__icontains=query) |
            Q(geography_id__name__icontains=query)
        )
        quarrygroup_ergebnisse = QuarryGroup.objects.filter(
            Q(name__icontains=query) | 
            Q(description__icontains=query)
        )
        sample_ergebnisse = Sample.objects.filter(
            Q(oeai_inventory_number__icontains=query) | 
            Q(notes__icontains=query) |
            Q(material_id__pref_label__icontains=query) |
            Q(quarry_id__name__icontains=query) |
            Q(quarry_group_id__name__icontains=query)
        )
        number_ergebnisse = Number.objects.filter(
            Q(oeai_inventory_number_id__oeai_inventory_number__icontains=query) | 
            Q(number__icontains=query) |
            Q(number_type__pref_label__icontains=query) |
            Q(oeai_inventory_number_id__oeai_inventory_number__icontains=query)
        )
        analyse_ergebnisse = Analyse.objects.filter(
            Q(oeai_inventory_number_id__oeai_inventory_number__icontains=query) |
            Q(analyse_type_id__pref_label__icontains=query)
        )

    context = {
        "query":query,
        "artifact_ergebnisse": artifact_ergebnisse,
        "geo_ergebnisse": geo_ergebnisse,
        "institution_ergebnisse": institution_ergebnisse,
        "project_ergebnisse": project_ergebnisse, 
        "quarry_ergebnisse": quarry_ergebnisse, 
        "quarrygroup_ergebnisse": quarrygroup_ergebnisse,
        "sample_ergebnisse": sample_ergebnisse,
        "number_ergebnisse": number_ergebnisse,
        "analyse_ergebnisse": analyse_ergebnisse
    }
    return render(request, "webpage/explore.html", context)

        

class AnalyseListView(GenericListView):

    model = Analyse
    filter_class = AnalyseListFilter
    formhelper_class = AnalyseFilterFormHelper
    table_class = AnalyseTable
    init_columns = [
        'id', 'oeai_inventory_number', 'analyse_type'
    ]
    # hier fehlt die überprüfung ob der User eingeloggt ist oder nicht
    exclude_columns = ['legacy_pk', 'fe', 'ion_f', 'notes_thinsections', 'mgco3','mn', 'sr', 'ion_li', 'ion_na',
                        'ion_k', 'ion_mg','ion_ca','ion_cl','ion_br','ion_j', 'ion_no3','ion_so4','ion_li_na',
                        'ion_k_na','ion_cl_na','ion_br_na','ion_i_na','ion_so4_na','ion_f_na','ion_no3_na', 
                        'iso_d18o','iso_d13c','icp_mg','icp_mn','icp_fe','icp_sr','icp_cr','icp_cr_n2o','icp_v',
                        'icp_y','icp_cd','icp_ba','icp_la','icp_ce','icp_pr','icp_dy','icp_ho','icp_yb','icp_pb',
                        'icp_u', 'notes_thinsection', 'epr_spectrometer', 'epr_spectral_height', 'epr_dolom', 
                        'epr_tot6', 'epr_spli', 'epr_int', 'epr_spread', 'epr_w', 'epr_stdintens', 'epr_stdintegr', 
                        'epr_stdw','epr_stdspli','pr_stdspread', 'epr_intens_standardised','epr_integr_standardised',
                        'epr_spli_standardised''epr_w_standardised', 'epr_spread_standardised','orig_data_csv',
                        'epr_stdspread', 'epr_spli_standardised', 'epr_w_standardised']
    
    ordering=['oeai_inventory_number']
    enable_merge = False


class AnalyseDetailView(BaseDetailView):

    model = Analyse
    template_name = 'archiv/generic_detail.html'


class AnalyseCreate(BaseCreateView):

    model = Analyse
    form_class = AnalyseForm
    template_name = 'archiv/generic_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(AnalyseCreate, self).dispatch(*args, **kwargs)


class AnalyseUpdate(BaseUpdateView):

    model = Analyse
    form_class = AnalyseForm
    template_name = 'archiv/generic_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(AnalyseUpdate, self).dispatch(*args, **kwargs)


class AnalyseDelete(DeleteView):
    model = Analyse
    template_name = 'webpage/confirm_delete.html'
    success_url = reverse_lazy('archiv:analyse_browse')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(AnalyseDelete, self).dispatch(*args, **kwargs)


class ArtifactListView(GenericListView):

    model = Artifact
    filter_class = ArtifactListFilter
    formhelper_class = ArtifactFilterFormHelper
    table_class = ArtifactTable
    init_columns = [
        'id','artefact_type','material','find_spot','storage_place'
    ]
    # hier fehlt die überprüfung ob der User eingeloggt ist oder nicht
    exclude_columns = ['legacy_pk', 'description', 'find_spot_extra', 'measurement', 'preservation', 
                       'dating', 'images', 'literature', 'orig_data_csv']
    enable_merge = False


class ArtifactDetailView(BaseDetailView):

    model = Artifact
    template_name = 'archiv/generic_detail.html'


class ArtifactCreate(BaseCreateView):

    model = Artifact
    form_class = ArtifactForm
    template_name = 'archiv/generic_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ArtifactCreate, self).dispatch(*args, **kwargs)


class ArtifactUpdate(BaseUpdateView):

    model = Artifact
    form_class = ArtifactForm
    template_name = 'archiv/generic_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ArtifactUpdate, self).dispatch(*args, **kwargs)


class ArtifactDelete(DeleteView):
    model = Artifact
    template_name = 'webpage/confirm_delete.html'
    success_url = reverse_lazy('archiv:artifact_browse')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ArtifactDelete, self).dispatch(*args, **kwargs)


class GeographyListView(GenericListView):

    model = Geography
    filter_class = GeographyListFilter
    formhelper_class = GeographyFilterFormHelper
    table_class = GeographyTable
    init_columns = [
        'id', 'name','identifier'
    ]
    ordering=['id']
    enable_merge = False


class GeographyDetailView(BaseDetailView):

    model = Geography
    #coords=serialize('geojson',Geography.objects.all()) #converts the shapefile loaded to geojson
    template_name = 'archiv/generic_detail.html'


class GeographyCreate(BaseCreateView):

    model = Geography
    form_class = GeographyForm
    template_name = 'archiv/generic_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(GeographyCreate, self).dispatch(*args, **kwargs)


class GeographyUpdate(BaseUpdateView):

    model = Geography
    form_class = GeographyForm
    template_name = 'archiv/generic_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(GeographyUpdate, self).dispatch(*args, **kwargs)


class GeographyDelete(DeleteView):
    model = Geography
    template_name = 'webpage/confirm_delete.html'
    success_url = reverse_lazy('archiv:geography_browse')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(GeographyDelete, self).dispatch(*args, **kwargs)


class InstitutionListView(GenericListView):

    model = Institution
    filter_class = InstitutionListFilter
    formhelper_class = InstitutionFilterFormHelper
    table_class = InstitutionTable
    init_columns = [
        'id', 'name','identifier'
    ]
    ordering=['name']
    enable_merge = False


class InstitutionDetailView(BaseDetailView):

    model = Institution
    template_name = 'archiv/generic_detail.html'


class InstitutionCreate(BaseCreateView):

    model = Institution
    form_class = InstitutionForm
    template_name = 'archiv/generic_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(InstitutionCreate, self).dispatch(*args, **kwargs)


class InstitutionUpdate(BaseUpdateView):

    model = Institution
    form_class = InstitutionForm
    template_name = 'archiv/generic_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(InstitutionUpdate, self).dispatch(*args, **kwargs)


class InstitutionDelete(DeleteView):
    model = Institution
    template_name = 'webpage/confirm_delete.html'
    success_url = reverse_lazy('archiv:institution_browse')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(InstitutionDelete, self).dispatch(*args, **kwargs)


class NumberListView(GenericListView):

    model = Number
    filter_class = NumberListFilter
    formhelper_class = NumberFilterFormHelper
    table_class = NumberTable
    init_columns = [
        'id', 'id','number','number_type','oeai_inventory_number'
    ]
    enable_merge = False


class NumberDetailView(BaseDetailView):

    model = Number
    template_name = 'archiv/generic_detail.html'


class NumberCreate(BaseCreateView):

    model = Number
    form_class = NumberForm
    template_name = 'archiv/generic_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(NumberCreate, self).dispatch(*args, **kwargs)


class NumberUpdate(BaseUpdateView):

    model = Number
    form_class = NumberForm
    template_name = 'archiv/generic_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(NumberUpdate, self).dispatch(*args, **kwargs)


class NumberDelete(DeleteView):
    model = Number
    template_name = 'webpage/confirm_delete.html'
    success_url = reverse_lazy('archiv:number_browse')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(NumberDelete, self).dispatch(*args, **kwargs)


class QuarryListView(GenericListView):

    model = Quarry
    filter_class = QuarryListFilter
    formhelper_class = QuarryFilterFormHelper
    table_class = QuarryTable
    init_columns = [
        'id', 'name','description'
    ]
    enable_merge = False
    ordering=['id']


class QuarryDetailView(BaseDetailView):

    model = Quarry
    template_name = 'archiv/generic_detail.html'


class QuarryCreate(BaseCreateView):

    model = Quarry
    form_class = QuarryForm
    template_name = 'archiv/generic_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(QuarryCreate, self).dispatch(*args, **kwargs)


class QuarryUpdate(BaseUpdateView):

    model = Quarry
    form_class = QuarryForm
    template_name = 'archiv/generic_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(QuarryUpdate, self).dispatch(*args, **kwargs)


class QuarryDelete(DeleteView):
    model = Quarry
    template_name = 'webpage/confirm_delete.html'
    success_url = reverse_lazy('archiv:quarry_browse')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(QuarryDelete, self).dispatch(*args, **kwargs)


class QuarryGroupListView(GenericListView):

    model = QuarryGroup
    filter_class = QuarryGroupListFilter
    formhelper_class = QuarryGroupFilterFormHelper
    table_class = QuarryGroupTable
    init_columns = [
        'id', 'name',
    ]
    enable_merge = False


class QuarryGroupDetailView(BaseDetailView):

    model = QuarryGroup
    template_name = 'archiv/generic_detail.html'


class QuarryGroupCreate(BaseCreateView):

    model = QuarryGroup
    form_class = QuarryGroupForm
    template_name = 'archiv/generic_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(QuarryGroupCreate, self).dispatch(*args, **kwargs)


class QuarryGroupUpdate(BaseUpdateView):

    model = QuarryGroup
    form_class = QuarryGroupForm
    template_name = 'archiv/generic_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(QuarryGroupUpdate, self).dispatch(*args, **kwargs)


class QuarryGroupDelete(DeleteView):
    model = QuarryGroup
    template_name = 'webpage/confirm_delete.html'
    success_url = reverse_lazy('archiv:quarrygroup_browse')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(QuarryGroupDelete, self).dispatch(*args, **kwargs)


class SampleListView(GenericListView):

    model = Sample
    filter_class = SampleListFilter
    formhelper_class = SampleFilterFormHelper
    table_class = SampleTable
    init_columns = [
        'id', 'oeai_inventory_number','material',
    ]

    # hier fehlt die überprüfung ob der User eingeloggt ist oder nicht
    exclude_columns = ['quarry_group','grain_size_max','grain_size_min', 'smell','color','color_description',
                    'color_kodak','stdcolor','weight','notes','sampling','image','literature', 'orig_data_csv']
    enable_merge = False


class SampleDetailView(BaseDetailView):

    model = Sample
    template_name = 'archiv/generic_detail.html'


class SampleCreate(BaseCreateView):

    model = Sample
    form_class = SampleForm
    template_name = 'archiv/generic_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SampleCreate, self).dispatch(*args, **kwargs)


class SampleUpdate(BaseUpdateView):

    model = Sample
    form_class = SampleForm
    template_name = 'archiv/generic_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SampleUpdate, self).dispatch(*args, **kwargs)


class SampleDelete(DeleteView):
    model = Sample
    template_name = 'webpage/confirm_delete.html'
    success_url = reverse_lazy('archiv:sample_browse')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SampleDelete, self).dispatch(*args, **kwargs)


def count_geo(request):
    current_task = count_geography.delay(1)
    return HttpResponse(f"Hey there! TASK-ID: {current_task.id}")


class TaskOveriewView(TemplateView):
    template_name = "archiv/task_overview.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['objects'] = TaskResult.objects.all()
        return context


class ProjectListView(GenericListView):

    model = Project
    filter_class = ProjectListFilter
    formhelper_class = ProjectFilterFormHelper
    table_class = ProjectTable
    init_columns = [
        'id','name'
    ]
    enable_merge = False

class ProjectDetailView(BaseDetailView):
    model = Project
    template_name = 'archiv/generic_detail.html'

class ProjectCreate(BaseCreateView):

    model = Project
    form_class = ProjectForm
    template_name = 'archiv/generic_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProjectCreate, self).dispatch(*args, **kwargs)
    
class ProjectUpdate(BaseUpdateView):

    model = Project
    form_class = ProjectForm
    template_name = 'archiv/generic_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProjectUpdate, self).dispatch(*args, **kwargs)
    
class ProjectDelete(DeleteView):
    model = Project
    template_name = 'webpage/confirm_delete.html'
    success_url = reverse_lazy('archiv:project_browse')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProjectDelete, self).dispatch(*args, **kwargs)
    
class ImageDetailView(BaseDetailView):
    model = Image
    template_name = 'archiv/generic_detail.html'

class ProjectsView(TemplateView):
    model = Project
    def get_context_data(self, **kwargs):
        objects = Project.objects.all()
        context = super().get_context_data(**kwargs)
        context['objects'] = objects
        return context
    template_name = 'infos/about.html'
