# Generated by Django 3.2.9 on 2021-11-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ZoteroItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zotero_key", models.CharField(max_length=20)),
                ("zotero_title", models.TextField(blank=True, null=True)),
                (
                    "zotero_creator",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("zotero_date", models.DateField(blank=True, null=True)),
                ("zotero_data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["zotero_creator", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ZoteroReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zotero_key", models.CharField(max_length=20)),
                ("zotero_title", models.TextField(blank=True, null=True)),
                (
                    "zotero_creator",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("zotero_date", models.DateField(blank=True, null=True)),
                ("zotero_data", models.JSONField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "ordering": ["zotero_creator", "id"],
                "abstract": False,
            },
        ),
    ]
