# Generated by Django 3.2.8 on 2021-11-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZoteroItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zotero_key', models.CharField(max_length=20)),
                ('zotero_title', models.TextField(blank=True, null=True)),
                ('zotero_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZoteroReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zotero_key', models.CharField(max_length=20)),
                ('zotero_title', models.TextField(blank=True, null=True)),
                ('zotero_data', models.JSONField(blank=True, null=True)),
                ('location', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
