# Generated by Django 3.2.8 on 2021-11-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zotero_ac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoteroitem',
            name='zotero_creator',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='zoteroitem',
            name='zotero_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zoteroreference',
            name='zotero_creator',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='zoteroreference',
            name='zotero_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
