# Generated by Django 3.2.8 on 2021-11-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zotero_ac', '0002_auto_20211114_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoteroreference',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
