# Generated by Django 3.2.8 on 2021-11-16 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zotero_ac', '0003_alter_zoteroreference_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zoteroitem',
            options={'ordering': ['zotero_creator', 'id']},
        ),
        migrations.AlterModelOptions(
            name='zoteroreference',
            options={'ordering': ['zotero_creator', 'id']},
        ),
    ]
