# Generated by Django 3.2.8 on 2021-11-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkosTechnicalCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_label', models.CharField(blank=True, help_text="e.g. 'Artifact__artefact_type", max_length=300, null=True, verbose_name='Model and property name')),
            ],
        ),
        migrations.RemoveField(
            model_name='skosconcept',
            name='collection',
        ),
        migrations.AddField(
            model_name='skosconcept',
            name='collection',
            field=models.ManyToManyField(blank=True, help_text='Collection that this concept is a member of', related_name='has_members', to='vocabs.SkosTechnicalCollection', verbose_name='member of skos:Collection'),
        ),
    ]
