# Generated by Django 3.2.8 on 2021-11-04 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0002_auto_20211104_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='skosconcept',
            name='tech_collection',
            field=models.ManyToManyField(blank=True, help_text='Collection that this concept is a member of', related_name='has_members', to='vocabs.SkosTechnicalCollection', verbose_name='member of skos:Collection'),
        ),
        migrations.RemoveField(
            model_name='skosconcept',
            name='collection',
        ),
        migrations.AddField(
            model_name='skosconcept',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Collection that this concept is a member of', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_members', to='vocabs.skoscollection', verbose_name='member of skos:Collection'),
        ),
    ]
