# Generated by Django 4.1.7 on 2023-05-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geography',
            options={'ordering': ['name'], 'verbose_name': 'Geography'},
        ),
        migrations.AddField(
            model_name='geography',
            name='orig_data_csv',
            field=models.TextField(blank=True, null=True, verbose_name='The original data'),
        ),
    ]
