# Generated by Django 3.2.8 on 2021-11-03 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geography',
            options={'ordering': ['name'], 'verbose_name': 'Geography'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['name'], 'verbose_name': 'Insititution'},
        ),
        migrations.AlterModelOptions(
            name='quarry',
            options={'ordering': ['name'], 'verbose_name': 'Quarry'},
        ),
        migrations.AlterModelOptions(
            name='quarrygroup',
            options={'ordering': ['name'], 'verbose_name': 'QuarryGroup'},
        ),
    ]
