# Generated by Django 3.2.8 on 2021-11-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0002_auto_20211112_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='epr_integr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standardised value of variables', max_digits=19, null=True, verbose_name='INTEGR Standardised'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='epr_intens',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standardised value of variables', max_digits=19, null=True, verbose_name='INTENS Standardised'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='epr_spli',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standardised value of variables', max_digits=19, null=True, verbose_name='SPLI Standardised'),
        ),
    ]
