# Generated by Django 4.1.7 on 2023-05-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0002_project_alter_number_options_alter_analyse_institute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='description of the project', null=True, verbose_name='description'),
        ),
    ]
