# Generated by Django 4.1.7 on 2023-05-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0002_alter_geography_options_geography_orig_data_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='geography',
            name='continent',
            field=models.CharField(blank=True, help_text='continent of the geographic location', max_length=250, null=True, verbose_name='continent'),
        ),
        migrations.AddField(
            model_name='geography',
            name='land',
            field=models.CharField(blank=True, help_text='land of the geographic location', max_length=250, null=True, verbose_name='land'),
        ),
        migrations.AddField(
            model_name='geography',
            name='location',
            field=models.CharField(blank=True, help_text='location of the geographic location', max_length=250, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='geography',
            name='province',
            field=models.CharField(blank=True, help_text='province of the geographic location', max_length=250, null=True, verbose_name='province'),
        ),
    ]
