# Generated by Django 3.2.8 on 2021-11-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0003_auto_20211112_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyse',
            old_name='epr_integr',
            new_name='epr_integr_standardised',
        ),
        migrations.RenameField(
            model_name='analyse',
            old_name='epr_intens',
            new_name='epr_intens_standardised',
        ),
        migrations.AddField(
            model_name='analyse',
            name='epr_spli_standardised',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standardised value of variables', max_digits=19, null=True, verbose_name='SPLI Standardised'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='epr_spli',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Line separation of doublet D6', max_digits=19, null=True, verbose_name='SPLI'),
        ),
    ]
