# Generated by Django 3.2.8 on 2021-11-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0003_auto_20211103_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='legacy_pk',
            field=models.IntegerField(blank=True, help_text='whatever', null=True, verbose_name='alt id'),
        ),
    ]
