# Generated by Django 4.1.7 on 2023-05-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0003_geography_continent_geography_land_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarry',
            name='images',
            field=models.CharField(blank=True, help_text='images', max_length=600, null=True, verbose_name='images'),
        ),
    ]
