# Generated by Django 3.2.8 on 2021-11-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0004_number_legacy_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='fe',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for fe', max_digits=19, null=True, verbose_name='Fe'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='icp_ba',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for icp_ba', max_digits=19, null=True, verbose_name='Ba'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='icp_cd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for icp_cd', max_digits=19, null=True, verbose_name='Cd'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='icp_ce',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for icp_ce', max_digits=19, null=True, verbose_name='Ce'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='icp_cr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for icp_cr', max_digits=19, null=True, verbose_name='Cr'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='icp_cr_n2o',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for icp_cr_n2o', max_digits=19, null=True, verbose_name='Cr (N2O)'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='icp_dy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for icp_dy', max_digits=19, null=True, verbose_name='Dy'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='icp_fe',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for icp_fe', max_digits=19, null=True, verbose_name='Fe'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='icp_ho',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for icp_ho', max_digits=19, null=True, verbose_name='Ho'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='icp_la',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for icp_la', max_digits=19, null=True, verbose_name='La'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='icp_mg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for icp_mg', max_digits=19, null=True, verbose_name='Mg'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='icp_mn',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for icp_mn', max_digits=19, null=True, verbose_name='Mn'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='icp_pb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for icp_pb', max_digits=19, null=True, verbose_name='Pb'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='icp_pr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for icp_pr', max_digits=19, null=True, verbose_name='Pr'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='icp_sr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for icp_sr', max_digits=19, null=True, verbose_name='Sr'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='icp_u',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for icp_u', max_digits=19, null=True, verbose_name='U'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='icp_v',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for icp_v', max_digits=19, null=True, verbose_name='V'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='icp_y',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for icp_y', max_digits=19, null=True, verbose_name='Y'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='icp_yb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for icp_yb', max_digits=19, null=True, verbose_name='Yb'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='ion_br',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for ion_br', max_digits=19, null=True, verbose_name='Br'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='ion_br_na',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for ion_br_na', max_digits=19, null=True, verbose_name='Br/Na'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='ion_ca',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for ion_ca', max_digits=19, null=True, verbose_name='Ca'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='ion_cl',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for ion_cl', max_digits=19, null=True, verbose_name='Cl'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='ion_cl_na',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for ion_cl_na', max_digits=19, null=True, verbose_name='Cl/Na'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='ion_f',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for ion_f', max_digits=19, null=True, verbose_name='Fe'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='ion_f_na',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for ion_f_na', max_digits=19, null=True, verbose_name='F/Na'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='ion_i_na',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for ion_i_na', max_digits=19, null=True, verbose_name='I/Na'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='ion_j',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for ion_j', max_digits=19, null=True, verbose_name='J'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='ion_k',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for ion_k', max_digits=19, null=True, verbose_name='K'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='ion_k_na',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for ion_k_na', max_digits=19, null=True, verbose_name='K/Na'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='ion_li',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for ion_li', max_digits=19, null=True, verbose_name='Li'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='ion_li_na',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for ion_li_na', max_digits=19, null=True, verbose_name='Li/Na'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='ion_mg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for ion_mg', max_digits=19, null=True, verbose_name='MgCO3'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='ion_na',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for ion_na', max_digits=19, null=True, verbose_name='Na'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='ion_no3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for ion_no3', max_digits=19, null=True, verbose_name='NO3'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='ion_no3_na',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for ion_no3_na', max_digits=19, null=True, verbose_name='NO3/Na'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='ion_so4',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for ion_so4', max_digits=19, null=True, verbose_name='SO4'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='ion_so4_na',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for ion_so4_na', max_digits=19, null=True, verbose_name='SO4/Na'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='iso_d13c',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for iso_d13c', max_digits=19, null=True, verbose_name='D13c (PDB)'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='iso_d18o',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for iso_d18o', max_digits=19, null=True, verbose_name='d18O (PDB)'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='mgco3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for mgco3', max_digits=19, null=True, verbose_name='MgCO3'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='mn',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for mn', max_digits=19, null=True, verbose_name='Mn'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='sr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='helptext for sr', max_digits=19, null=True, verbose_name='Sr'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='weight of the sample', max_digits=19, null=True, verbose_name='weight'),
        ),
    ]
