# Generated by Django 4.1.7 on 2023-05-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0004_quarrygroup_quarry'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='project',
            field=models.ManyToManyField(help_text='project artefact', related_name='Artefact_Project', to='archiv.project'),
        ),
        migrations.AddField(
            model_name='sample',
            name='project',
            field=models.ManyToManyField(help_text='project sample', related_name='Sample_Project', to='archiv.project'),
        ),
    ]
