# Generated by Django 3.2.8 on 2021-11-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zotero_ac', '0002_auto_20211114_1458'),
        ('archiv', '0004_auto_20211112_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='reference',
            field=models.ManyToManyField(blank=True, help_text='please provide some', related_name='reference_for_artefact', to='zotero_ac.ZoteroReference', verbose_name='Literatur'),
        ),
        migrations.AddField(
            model_name='quarry',
            name='reference',
            field=models.ManyToManyField(blank=True, help_text='please provide some', related_name='reference_for_quarry', to='zotero_ac.ZoteroReference', verbose_name='Literatur'),
        ),
        migrations.AddField(
            model_name='sample',
            name='reference',
            field=models.ManyToManyField(blank=True, help_text='please provide some', related_name='reference_for_sample', to='zotero_ac.ZoteroReference', verbose_name='Literatur'),
        ),
    ]
