# Generated by Django 4.1.7 on 2023-05-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0004_alter_quarry_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarry',
            name='images',
            field=models.TextField(blank=True, help_text='images', null=True, verbose_name='images'),
        ),
    ]
