# Generated by Django 4.1.7 on 2023-05-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0005_artifact_project_sample_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contact_email',
            field=models.CharField(blank=True, help_text='contact email of the project', max_length=250, null=True, verbose_name='contact email'),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_name',
            field=models.CharField(blank=True, help_text='contact name of the project', max_length=250, null=True, verbose_name='contact name'),
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.CharField(blank=True, help_text='URL of the project', max_length=250, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='icp_mg',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='helptext for icp_mg', max_digits=19, null=True, verbose_name='Mg'),
        ),
    ]
