# Generated by Django 3.2.8 on 2021-11-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0005_auto_20211115_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['name'], 'verbose_name': 'Institution'},
        ),
    ]
