# Generated by Django 4.1.7 on 2023-06-20 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0005_alter_quarry_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='images',
            field=models.TextField(blank=True, help_text='images of the artefact', null=True, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='literature',
            field=models.TextField(blank=True, help_text='literature', null=True, verbose_name='literature'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('image_stream', models.TextField(blank=True, help_text='image', null=True, verbose_name='image_stream')),
                ('description', models.TextField(blank=True, help_text='description of the image', null=True, verbose_name='description')),
                ('analyse_id', models.ForeignKey(blank=True, help_text='images of the analyse ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Images_Artefact', to='archiv.analyse', verbose_name='analyse_id')),
                ('artefact_id', models.ForeignKey(blank=True, help_text='images of the artefact ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Images_Artefact', to='archiv.artifact', verbose_name='artefact_id')),
                ('quarry_id', models.ForeignKey(blank=True, help_text='images of the quarry ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Images_Quarry', to='archiv.quarry', verbose_name='quarry_id')),
            ],
            options={
                'verbose_name': 'Images',
                'ordering': ['quarry_id'],
            },
        ),
    ]
