# Generated by Django 3.2.8 on 2021-11-16 10:07

import archiv.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0006_alter_institution_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(storage=archiv.storage.OverwriteStorage(), upload_to='archiv/data')),
            ],
        ),
    ]
