# Generated by Django 3.2.8 on 2021-11-16 10:09

import archiv.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0007_datasheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='upload',
            field=models.FileField(blank=True, null=True, storage=archiv.storage.OverwriteStorage(), upload_to='archiv/data'),
        ),
    ]
