# Generated by Django 4.1.7 on 2023-12-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0008_images_easydb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse',
            name='open_access',
            field=models.BooleanField(blank=True, default=False, help_text='open access', null=True, verbose_name='open access'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='open_access',
            field=models.BooleanField(blank=True, default=False, help_text='open access', null=True, verbose_name='open access'),
        ),
    ]
